#!/bin/bash

# gswann 16 Feb 2021
#
# 17 Feb 2021
# added microSD card to home assistant and moved datbase to it.
# All the high number of writes now go to the card.
# Later added a USB hard drive and mapped database to it.  Works better.

clear
echo "System is $HOSTNAME"
uptime

echo -ne 'Seconds uptime: '
secsup=$(awk '{print $1}' /proc/uptime)
echo $secsup

echo
echo -ne 'System disk: '
mydisk=$(mount | grep '/ ' | awk '{print $1}' | cut -c6-14 | awk '{printf $0}') 
echo $mydisk

echo -ne 'Data disk:   '
datadisk=$(mount | grep '/media-db2' | awk '{print $1}' | cut -c6-14 | awk '{printf $0}') 
echo $datadisk

echo -ne "Number of system disk writes since boot: "
numwrites=$(cat /proc/diskstats | grep "$mydisk" | head -n1 | awk '{printf $8}')
echo $numwrites

echo -ne "Number of data disk writes since boot:   "
numdwrites=$(cat /proc/diskstats | grep "$datadisk" | head -n1 | awk '{printf $8}')
echo $numdwrites

echo
echo -ne "Writes per second to system disk $mydisk: " 
wps=$(echo - | awk "{print $numwrites / $secsup}") 
echo $wps

echo -ne "Writes per second to data disk $datadisk: "
wps=$(echo - | awk "{print $numdwrites / $secsup}")
echo $wps
echo

df -h
echo -e 
lsblk
